#+TITLE: Richard Davis, Compositeur
#+SUBTITLE: A propos
#+AUTHOR: Richard Davis
#+SETUPFILE: ../../common/theme-readtheorg.setup

#+INCLUDE: ../../common/header-fr.org

* Introduction
:PROPERTIES:
:CUSTOM_ID: press-introduction
:END:

Salutations !
Je m'appelle Richard Davis.
Je suis compositeur, altiste et professeur, basé à Montréal et au Massachusetts.
Mes principaux intérêts en matière de composition sont l'intertextualité, l'électronique en direct, la musique vocale ou à émulation vocale, et la composition assistée par ordinateur.
Avec l'alto, je me spécialise dans l'interprétation de la musique contemporaine.

* Bio
:PROPERTIES:
:CUSTOM_ID: press-bio
:END:

Richard Davis est un compositeur qui s'intéresse principalement à l'intertextualité, à l'électronique en direct, à la musique vocale ou à émulation vocale et à la composition assistée par ordinateur. Il est également altiste et se consacre principalement à l'interprétation de la musique contemporaine.
Richard est originaire de Westford, Massachusetts, aux États-Unis, et réside actuellement à Montréal.

Récemment, Richard a achevé son travail en tant que premier étudiant compositeur en résidence au studio vocal de McGill, qui a abouti à la première mondiale en 2022 de son opéra fātō profugī, qui présente un commentaire intertextuel sur l'histoire originale de Didon et Énée, tirée de l'Énéide de Vergile.

À la suite de ce projet, Richard a également collaboré avec l'altiste Marilou Lepage sur sa pièce "Variations on an Excerpt", pour alto solo et électronique en direct.

Plus récemment, Richard a collaboré avec la vocaliste Dani Claxton pour produire "Till This Moment", une œuvre dramatique pour vocaliste et électronique en direct qui explore des scènes cruciales de "Pride and Prejudice" de Jane Austen.

Richard Davis est titulaire d'un baccalauréat en composition de l'École de musique Schulich de l'Université McGill, où il a étudié la composition musicale avec le professeur Sean Ferguson et l'interprétation à l'alto avec le professeur André Roy.
Dans le cadre de ce même programme, il a également obtenu un B.A. Minor Concentration in computer science.
Il est actuellement candidat à la maîtrise en musique à Schulich, où il étudie la composition musicale avec le professeur Jean Lesage.

* CV

Voici un lien vers mon [[https://davisrichard437.github.io/documents/Richard Davis - CV.pdf][CV]] pour les personnes intéressées.
