#+TITLE: Richard Davis, Composer
#+SUBTITLE: About
#+AUTHOR: Richard Davis
#+SETUPFILE: ../../common/theme-readtheorg.setup

#+INCLUDE: ../../common/header.org

* Bio
:PROPERTIES:
:CUSTOM_ID: press-bio
:END:

Richard Davis is a composer, whose primary interests are intertextuality, live electronics, vocal or vocal-emulating music, and computer-assisted composition, and a violist, whose main focus is contemporary music performance.
Richard is from Westford, Massachusetts in the US and currently resides in Montreal.

Recently, Richard completed his work as the first student composer in residence with the McGill vocal studio, culminating in the 2022 world premiere of his operatic work fātō profugī, which presents an intertextual commentary on the original Dido and Aeneas story from Vergil’s Aeneid.

Following the conclusion of this project, Richard also completed a collaboration with violist Marilou Lepage on his piece "Variations on an Excerpt," for solo viola and live electronics.

Furthermore, in 2021, "Perpetuum," another of Richard’s works for soprano and small ensemble and composed after text by Celine Wang, had its premiere.
Additionally, two of his other works—his multi-movement duo for flute and clarinet, Divide, and his Two Pieces for Piano—were recorded that same year.
On the performance side of things, Richard has premiered numerous works by living composers, including Omer Barash’s /OTOT/, Philippe Macnab-Séguin’s /Tehom/, and Kit Vaughan Soden’s /Overture/ with the McGill Symphony Orchestra, and Marilou Buron’s /Qui croire de soi?/ with McGill’s Contemporary Music Ensemble.

Richard Davis has a high school diploma from Westford Academy, and is currently a
B.Mus. candidate at the Schulich School of Music of McGill University, where he is studying music composition under Professor Sean Ferguson and viola performance under Professor André Roy.

* CV

Here is a link to my [[https://davisrichard437.github.io/documents/Richard Davis - CV.pdf][CV]] for those interested.
