#+TITLE: Richard Davis, Composer
#+SUBTITLE: Events
#+AUTHOR: Richard Davis
#+SETUPFILE: ../../common/theme-readtheorg.setup

#+INCLUDE: ../../common/header-en.org

* Upcoming
:PROPERTIES:
:CUSTOM_ID: events-upcoming
:END:

Nothing at the moment!

* Recent

** DCS Concert <2023-04-14 Fri 15:00>

Dani Claxton will be performing my work "Till this Moment" for solo vocalist and electronics at the upcoming Digital Composition Studio's Class Concert.

"Till This Moment" is a piece for voice and live electronics that adapts the pivotal chapters of Jane Austen's /Pride and Prejudice/---Mr. Darcy's letter and Elizabeth Bennet's reaction to it.
In reading this letter, Elizabeth is confronted with information incompatible with her current worldview, first denying its contents, then considering it more carefully, and finally understanding its truth, ultimately leaving her a transformed and improved person.
The mixed format enables the construction of a dramatic dichotomy between representations of Elizabeth's conscious will, as presented by the performer, and those of the forces exerted upon her by her character, her peers, and the narrative---in a word, her soul---which are reflected within the electronics.

** MASC Concert <2023-03-19 Sun 20:00>

My 2019 solo clarinet work "One need not be a Chamber" will be performed by clarinetist Alexander Ortins and narrated by Dani Claxton at the McGill Association of Student Composers' [[https://www.mcgill.ca/music/channels/event/mcgill-association-student-composers-concert-342228][Winter Concert]].

"One need not be a Chamber" is a work for solo clarinet and optional narrator, based on the Emily Dickinson poem "One need not be a Chamber---to be Haunted---".
The music maintains an intimate, line-by-line relationship with the poem, translating various motifs and features of the text into leitmotifs---in the loosest sense---that accompany the emotional arc of Dickinson's poem.

